TRIAL_DAYS = 7

DEFAULT_CURRENCY = "UZS"
DEFAULT_TIMEZONE = "Asia/Tashkent"

DEFAULT_MAX_PRODUCTS = 100
DEFAULT_MAX_USERS = 2

OTP_CODE_TTL_SECONDS = 300
OTP_VERIFICATION_TOKEN_TTL_SECONDS = 600
OTP_RESEND_COOLDOWN_SECONDS = 60
OTP_MAX_ATTEMPTS = 5
